### ISSUE TITLE
miner-genesis-init-container fail

### ISSUE THREAD

**Issue by JPyml** [MaximilianMeister/kuberneteth#11] opened 2018-04-20 12:05 UTC
Hi,

I'm trying to deploy kuberneteth on my kubeadm cluster v1.10 but none miner containers can't run (it's in pending) because it wait for miner-genesis-init-container. 
But my miner-genesis-init-container can't mkdir and touch in the volume mount because it haven't enough right : http://prntscr.com/j7sris
I don't know what i can do ?

**Comment by JPyml** [comment] 2018-04-20 12:26
I just chmod and still the same issue : http://prntscr.com/j7t4zk

**Comment by MaximilianMeister** [comment] 2018-04-20 12:28
this is probably due to the usage of [hostPath](https://kubernetes.io/docs/concepts/storage/volumes/#hostpath) which is very limited, i wonder if it makes sense to switch to [local](https://kubernetes.io/docs/concepts/storage/volumes/#local) at some point

> I just chmod and still the same issue : http://prntscr.com/j7t4zk

can you try `chown` with whatever user is in charge of the container?

**Comment by JPyml** [comment] 2018-04-20 12:34
I run my kubernetes with my root account but I have try with my commun user but i have still the same issue

**Comment by MaximilianMeister** [comment] 2018-04-20 12:43
@JPyml ok, i'll try to reproduce the issue. thanks for the report

**Comment by Strydom** [comment] 2018-05-01 11:46
It looks like this could be related to https://github.com/ethereum/go-ethereum/issues/16464

The new docker images doesn't run with root permissions...

**Comment by MaximilianMeister** [comment] 2018-05-02 06:41
> It looks like this could be related to ethereum/go-ethereum#16464
> 
> The new docker image does not run with root permissions...

@Strydom good catch! thanks for the hint

**Comment by InflatibleYoshi** [comment] 2018-05-03 19:51
@MaximilianMeister In node.toml.erb, Line 50 there's a typo
`HTTPModules = ["db", "eth", "net", "web3", "personal", "web3"]`
Replace the second web3 with "miner" and it worked for me.

**Comment by MaximilianMeister** [comment] 2018-05-09 07:11
this is fixed in geth since release 1.8.6 [see here](https://github.com/ethereum/go-ethereum/pull/16052#issuecomment-383567275)

the [breaking PR](https://github.com/ethereum/go-ethereum/pull/16052) has been [reverted](https://github.com/ethereum/go-ethereum/pull/16552)

i've tested it on k8s 1.9.7 but I assume it is fixed as well on 1.10

@JPyml would be great if you can test it with a geth version >= 1.8.6 again, but i'll close the issue for now. feel free to reopen when it is still broken

thanks for the help

**Closed by MaximilianMeister** 2018-05-09 07:11 UTC
